// src/App.tsx
import React, { useState } from 'react';
import './App.css';

interface FeedItem {
  link: string | null | undefined;
  title: string | null| undefined;
  thumbnail: string | null | undefined;
  description: string | null | undefined;
}

export default function App() {
  const [rssUrl, setRssUrl] = useState("");
  const [items, setItems] = useState<FeedItem[]>([]);

  const handleOnChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setRssUrl(event.target.value)
  };

  const getRss = async (event: React.FormEvent<HTMLFormElement>) => {
    // Preventing the page from reloading
    event.preventDefault();
    const res = await fetch(`https://api.allorigins.win/get?url=${rssUrl}`);
    const { contents } = await res.json();
    const feed = new window.DOMParser().parseFromString(contents, "text/xml");
    const items = feed.querySelectorAll("item");
    const feedItems = [...items].map((el: Element) => ({
      link: el.querySelector("link")?.textContent,
      title: el.querySelector("title")?.textContent,
      thumbnail: el.querySelector("thumbnail")?.getAttribute("url"),
      description: el.querySelector("description")?.textContent?.replace(/<[^>]+>/g, '')
    }));
    console.log(feedItems);
    setItems(feedItems);
  }

  return (
    <div className='container'>
       <h4>URL</h4>
       <form onSubmit={getRss}>
       <input
          type="url"
          name="rssUrl"
          id="rssUrl"
          placeholder="https://www.example.com/.rss"
          onChange={(e) => handleOnChange(e) }
          required
        />
        <button type='submit'>Submit</button>
       </form>
       { items.map((item) => {
        return (
          <div className='article'>
          <div className='article-image'>
            <img src={item.thumbnail ? item.thumbnail : ""} />
          </div>
          <div className='article-info'>
            <h2>{item.title}</h2>
            <p>{item.description}</p>
            <a target="_blank" rel="noreferrer" href={item.link ? item.link : ""}>
              <button>Read article</button>
            </a>
          </div>
         </div>
        )
       })}
       </div>
  );
}

// src/App.vue
<template>
  <div id="app" class="container mx-auto p-4">
    <h1 class="text-2xl font-bold mb-4 text-center">RSS Reader</h1>
    <form @submit.prevent="fetchRSS" class="mb-4">
      <input
        v-model="rssUrl"
        placeholder="Enter RSS feed URL"
        class="border p-2 rounded w-full mb-2"
      />
      <button type="submit" class="bg-blue-800 text-white p-2 rounded w-full">
        Fetch RSS
      </button>
    </form>
    <div v-if="feed" class="mt-4">
      <h2 class="text-xl font-semibold mb-2">{{ feed.title }}</h2>
      <ul>
        <li v-for="item in feed.items" :key="item.link" class="mb-4">
          <a :href="item.link" target="_blank" class="text-blue-600 font-medium hover:underline">{{ item.title }}</a>
          <div v-html="item.description" class="mt-1"></div>
        </li>
      </ul>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue'

interface FeedItem {
  title: string
  link: string
  description: string
}

interface Feed {
  title: string
  items: FeedItem[]
}

export default defineComponent({
  name: 'App',
  setup() {
    const rssUrl = ref<string>('')
    const feed = ref<Feed | null>(null)

    const fetchRSS = async () => {
      try {
        const response = await fetch(`https://api.rss2json.com/v1/api.json?rss_url=${rssUrl.value}`)
        const data = await response.json()
        feed.value = {
          title: data.feed.title,
          items: data.items.map((item: any) => ({
            title: item.title,
            link: item.link,
            description: item.description
          }))
        }
      } catch (error) {
        console.error('Error fetching RSS feed:', error)
      }
    }

    return {
      rssUrl,
      feed,
      fetchRSS
    }
  }
})
</script>

<style scoped>
/* No custom styles needed */
</style>
